title: "Red Team Mind"
description: "Pentesting físico, ingeniería social, OSINT y psicología aplicada a la seguridad."
theme: jekyll-theme-hacker
show_downloads: false
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title:output_ext
