title: "Red Team Mind — TomDoe"
description: "Pentesting físico, ingeniería social, OSINT y psicología aplicada a la ciberseguridad."
theme: jekyll-theme-hacker
show_downloads: false
markdown: kramdown
